# This workflow will install Python dependencies, run tests and create a coverage report.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests_and_coverage

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        python -m doctest README.md
        python -m doctest docs/source/quickstart.rst
        pytest --doctest-modules --junitxml=junit/test-results-${{ matrix.os }}-py${{ matrix.python-version }}.xml --cov=mlqa --cov-report=xml --cov-report=html
    - name: Upload pytest test results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results-${{ matrix.os }}-py${{ matrix.python-version }}
        path: junit/test-results-${{ matrix.os }}-py${{ matrix.python-version }}.xml
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        directory: ./
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: ./codecov_report_${{ matrix.os }}_py${{ matrix.python-version }}.gz
